@startuml inmroRPG Class Diagram
'https://plantuml.com/en/class-diagram
'good https://real-world-plantuml.com/umls/4780185589121024
' ok https://real-world-plantuml.com/umls/4727890604195840
'typescript interface example https://real-world-plantuml.com/umls/4780185589121024
' o-> hagregation! =/ composition *->


class Story {
  -storyID : ObjID
  -storyName : Sting
  -storyTheme : [Sring]
  -created : Date
  -lastEdit : Date
  -participants : [Participant]
  -contents : [contentNode]

  constructor(storyID : ObjID, storyName : Sting, storyTheme : [String], created : Date)
  storyInfo()
  printStory()
  fight()
  attendanceSwitch(player)
}

class Player {
  -playerId : ObjID
  -name : String
  -email : String
  -password : #String
  -preferences : [Preference]
  -lastActive : Date
  -created : Date
  -reports : [Report]

  constructor(playerId : ObjID, name : String, email : String, password : #String)
  get playerID()
  get playerName()
  set playerName()
  get playerMail()
  set playerMail()
  get playerPassword()
  set playerPassword()
  get playerPreferences()
  set playerPreferences()
  get playerActive()
  set playerActive()

  get addReport(reportingPlayer, reportedTxt)
  set addReport(reportedPlayer, reportTxt)
  get playerInfo()
  addContent(Story, ContentNode)
}

class storyNode {
  -storyDate : DATE
  -storyText : String
  -playerCreator : playerID
  -option : BOOL
  -figth : BOOL
  -branch : ???

  constructor( storyDate : DATE, storyText : String, playerCreator : playerID)
}

Player "1" o-- "0..*" storyNode
Story "1" o-- "0..*" storyNode


@enduml