<script>
import { mapActions } from 'vuex'

export default {
  name: 'newStory',
  data() {
    return {
      storyName: '',
      storyTheme: [],
      storyCover: '',
      backendError: null
    }
  },
  methods: {
    ...mapActions(['createStory']),
    async createNewStory(e) {
      e.preventDefault()

      try {
        await this.createStory({
          storyName: this.storyName,
          storyTheme: this.storyTheme,
          storyCover: this.storyCover
        })

        this.$router.push('/')
      } catch (e) {
        this.backendError = e.response.data.message
      }
    }
  }
}
</script>

<template lang="pug">

.container-fluid
  .row
    .col-md-4.offset-md-4
      .story-form.bg-light.p-4.pb-5.my-5
        form.row.g-3(@submit="createNewStory")
          h4.pb-0.mb-0 Create a new Story!
          p.pt-0.mt-0 Set some basics
          .col-12
            label(for="storyName") Name Your Story
            input.form-control.mt-1(v-model="storyName" id="storyName" type="text" placeholder="Storyname" required)
          .col-12
            label(for="storyTheme")
              |Add max. 3 Themes for your Story
              br
              |(e.g. Fantasy, Dungeon, ...  )
            input.form-control.mt-1(v-model="storyTheme[0]" name="storyTheme" id="storyTheme" type="text" placeholder="a theme")
            input.form-control.mt-1(v-model="storyTheme[1]" name="storyTheme" id="storyTheme" type="text" placeholder="another theme")
            input.form-control.mt-1(v-model="storyTheme[2]" name="storyTheme" id="storyTheme" type="text" placeholder="last theme")
          .col-12
            label(for="storyCover") Coverimage will be Generated by your Seed!
            input.form-control.mt-1(v-model="storyCover" id="storyCover" type="text" placeholder="something.jpg" required)
          //- .col-12
          //-   .form-check
          //-     input#rememberMe.form-check-input(type='checkbox')
          //-     label.form-check-label(for='rememberMe')  Remember me
          .col-12
            button.btn.btn-primary.form-control(type="submit" value="createNewStory") Create Your Story!
          .col-12
            div(v-if="backendError") {{ backendError }}
        hr.mt-4
        .col-12
          p.text-center.mb-0
            p.mb-0.pb-0 Skip and select another story?&nbsp;
            router-link.mt-0.pt-0(to="/") Select one!

</template>
<style lang="scss" scoped></style>
